export const arrPaginasIniciais = [
    "Esposas de Henrique VIII",
    "Cometa de César",
    "Defenestrações de Praga",
    "Arca da Aliança",
    "Biblioteca perdida de Ivã, o Terrível",
    "Saque de Roma (410)",
    "Ouro de Tolosa",
    "Amaro Pargo",
    "Três Irmãos (joia)",
    "Os Juízes Justos",
    "Ovo Fabergé",
    "RMS Republic (1903)",
    "Roubo de diamantes em Antuérpia",
    "Masamune",
    "Comboio fantasma nazi",
    "Câmara de Âmbar",
    "Joias da Coroa Francesa",
    "Lista de papas sexualmente ativos",
    "Orientação do papel higiênico",
    "Velha Tjikko",
    "Jaya Sri Maha Bodhi",
    "Adansonia digitata",
    "Árvore do Ténéré",
    "Árvore da Ciência do Bem e do Mal",
    "Cajueiro de Pirangi",
    "Máquina de Anticítera",
    "Mapa de Piri Reis",
    "Grande Mancha Vermelha",
    "Cintura de asteroides",
    "Colina mamelonar",
    "Lao Zi",
    "Preste João",
    "Aláqueme Bianre Alá",
    "Legio IX Hispana",
    "Plínio, o Velho",
    "Plínio, o Jovem",
    "Incitato",
    "Timothy Dexter",
    "Tarrare",
    "Inês de Castro",
    "Sínodo do Cadáver",
    "Nicolau Copérnico",
    "Otto Skorzeny",
    "Adrian Carton de Wiart",
    "Culinária da Escócia",
    "Guerra dos Chimpanzés de Gombe",
    "Batalha de B-R5RB",
    "Nils Olav",
    "Incêndio de uísque em Dublin",
    "TempleOS",
    "Guerra do Porco",
    "Batalha pelo Castelo Itter",
    "Tentativas de assassinato a Fidel Castro",
    "Inundação de melaço de Boston",
    "Olga de Kiev",
    "Unidade 731",
    "Pickles",
    "Flocke",
    "Knut (urso-polar)",
    "Larry (gato)",
    "Paul (polvo)",
    "Messi (cão)",
    "Moo Deng",
    "Nora (gato)",
    "Patron (cão)",
    "Stepan",
    "Blondi",
    "Bucéfalo",
    "Hanno (elefante)",
    "Marengo (cavalo)",
    "Alex (papagaio)",
    "Hans Esperto",
    "Kanzi",
    "Koko (gorila)",
    "Lady Wonder",
    "Jonathan (tartaruga)",
    "Harriet (tartaruga)",
    "George Solitário",
    "Ilha-fantasma",
    "Ilha Nula",
    "Lago Nyos",
    "Escada de Jacó (Jamestown)",
    "Meteorito Hoba",
    "Pedículo do Congo",
    "Akon City (Senegal)",
    "Umoja",
    "Ilha Tromelin",
    "Socotorá",
    "República de Benim (1967)",
    "Cachoeiras de Sangue",
    "Cratera de Darvaza",
    "Principado de Sealand",
    "Placa de reclamação a Ea-nasir",
    "Heliogábalo",
    "Papa Bento IX",
    "Papa Celestino V",
    "Contatos transoceânicos pré-colombianos",
    "Batalhão Sagrado de Tebas",
    "Saneamento na Civilização do Vale do Indo",
    "Silbanaco",
    "Relações sino-romanas",
    "Wise Men of Gotham",
    "Revolta de Nica",
    "João I de França",
    "Verme-da-mongólia",
    "Chupacabra",
    "Drop bear",
    "Besta de Gévaudan",
    "Vaca esférica",
    "Squonk",
    "Tarasca",
    "Demônio de Jersey",
    "Homem do distintivo",
    "Dan Burros",
    "Enterro celestial",
    "Esmagamento por elefante",
    "Fotografia com pombos",
    "Movimento antitabagista na Alemanha nazista",
    "Sentido da vida",
    "Se uma árvore cai em uma floresta",
    "Cymothoa exigua",
    "Gato de olho ímpar",
    "Tubarão-duende",
    "Prostituição em animais",
    "Selfies da macaca",
    "Baarle-Hertog",
    "Baarle-Nassau",
    "Badlands Guardian",
    "Bir Tawil",
    "Centralia (Pensilvânia)",
    "Cidade murada de Kowloon",
    "Conspiração de Bielefeld",
    "Coober Pedy",
    "Cândido Godói",
    "Ferdinand Cheval",
    "Ferdinandea",
    "Fordlândia",
    "Joker Stairs",
    "Märket",
    "Mill Ends Park",
    "Moresnet",
    "Oblast Autônomo Judaico",
    "Ossuário de Sedlec",
    "Terra de Marie Byrd",
    "0 de janeiro",
    "0,999...",
    "30 de fevereiro",
    "Ano zero",
    "Dagen H",
    "Dia do Pi",
    "Emissoras de números",
    "Hexacosioi-hexeconta-hexafobia",
    "Número de Graham",
    "Número primo ilegal",
    "Problema do ano 2038",
    "Bushismo",
    "Disco de Festo",
    "Engrish",
    "Leet",
    "Mamihlapinatapai",
    "Manuscrito Voynich",
    "Trema do metal",
    "Pikachurina",
    "Sonic hedgehog",
    "Vespa-joia",
    "Astronauta Caído",
    "Abigail e Brittany Hensel",
    "Bloop",
    "Café com leite cósmico",
    "Charles Domery",
    "Escala de Bristol",
    "Caso Sokal",
    "Espiral de Ulam",
    "Galle (cratera marciana)",
    "Ginecomastia",
    "Hipertricose",
    "Lina Medina",
    "Chuva de animais",
    "Mary Toft",
    "Hilaridade fatal",
    "Observatório do Vaticano",
    "Oopart",
    "Projeto MKULTRA",
    "Ota Benga",
    "Paradoxo do corvo",
    "Cotão",
    "Phineas Gage",
    "Rochas deslizantes de Racetrack Playa",
    "Gosma cinza",
    "Problema de Monty Hall",
    "Picrete",
    "Rei dos ratos",
    "Síndrome de Capgras",
    "Síndrome de Cotard",
    "Síndrome de Jerusalém",
    "Síndrome de Stendhal",
    "Síndrome da mão alheia",
    "Síndrome do sotaque estrangeiro",
    "Teorema da bola cabeluda",
    "Teorema do macaco infinito",
    "Terra oca",
    "Trepanação",
    "Trimetilaminúria",
    "Triscaidecafobia",
    "Vale da estranheza",
    "Epidemia de dança de 1518",
    "Linha do tempo do futuro distante",
    "Voyager Golden Record",
    "Alejandro Cao de Benós",
    "Complexo de vira-lata",
    "Dobri Dobrev",
    "Jeanne Calment",
    "Joshua Norton",
    "Muntadhar al-Zaidi",
    "Thomas Midgley",
    "Tsutomu Yamaguchi",
    "Bild Lilli",
    "The Day the Clown Cried",
    "Manic Pixie Dream Girl",
    "100 Years",
    "Efeito Tetris",
    "Enterro de jogos eletrônicos da Atari",
    "I Love Bees",
    "JFK Reloaded",
    "Killer 7",
    "Telejogo",
    "Escopetarra",
    "GG Allin",
    "Mais populares que Jesus",
    "Homossexualidade e vampiros",
    "Questão da autoria das obras de Shakespeare",
    "All your base are belong to us",
    "Kilroy was here",
    "Countryballs",
    "Tourist Guy",
    "Kryptos",
    "Merda de Artista",
    "Apolônio de Carvalho",
    "Delírio de cristal",
    "Eduard Bloch",
    "Estudo da sífilis não tratada de Tuskegee",
    "Grande engodo da Lua",
    "Hospital Colônia de Barbacena",
    "Juan Pujol García",
    "Ranieri Mazzilli",
    "Massacre de Haximu",
    "Motim do HMS Bounty",
    "Operação Brother Sam",
    "Operação Condor",
    "Ouro de Moscou",
    "Violet Jessop",
    "Queima dos arquivos da escravidão no Brasil",
    "William Walker",
    "Zoológico humano",
    "Marvin Heemeyer",
    "Risco aviário",
    "Maid café",
    "Tesouro de Fenn",
    "Cinocéfalo",
    "Fadas de Cottingley",
    "Mapinguari",
    "Carlo Acutis",
    "Igreja Maradoniana",
    "Igreja do Subgênio",
    "Movimento Príncipe Philip",
    "Hiroo Onoda",
    "Vasili Arkhipov",
    "Stanislav Petrov",
    "Wojtek",
    "Elizabeth Holmes",
    "Incidente do dildo de Waitangi",
    "Pantone 448 C",
    "Andrei Chikatilo",
    "Mike, o frango sem cabeça",
    "Jimmy Carter e o incidente do coelho",
    "Prémios Darwin",
    "Incidente do Passo Dyatlov",
    "Desaparecimento de Valentich",
    "Ereção post mortem",
    "Morte durante o sexo consensual",
    "Morte por coco",
    "Mistério das máscaras de chumbo",
    "Henry Lee Lucas",
    "Bicicleta-fantasma",
    "Mordred",
    "Ablutofobia",
    "Polidactilia",
    "Bialbero di Casorzo",
    "33 Thomas Street",
    "Desaparecimento do Boeing 727-223 em 2003",
    "Desastre de Le Mans em 1955",
    "Jogos Olímpicos de Verão de 1936",
    "Lenda do soldado transportado de 1593",
    "Albert Pierrepoint",
    "Albert Fish",
    "Voo Aeroflot 593",
    "ADX Florence",
    "Expedição polar de S. A. Andrée",
    "Anatoly Moskvin",
    "Anatoli Bugorski",
    "Amelia Earhart",
    "Aum Shinrikyo",
    "Bode Ioiô",
    "Max II",
    "Fosfeno",
    "Prometheus (árvore)",
    "Rosemary Kennedy",
    "Franz Kafka",
    "Ilusão do rosto oco",
    "Cérebro de Boltzmann",
    "Fotografia pós-morte",
    "Tubarão-branco",
    "Ted Kaczynski",
    "Drácon",
    "Maldição do faraó",
    "Dilúvio de cerveja de Londres",
    "Cratera de Chicxulub",
    "Erupção de raios gama",
    "Cometa Shoemaker-Levy 9",
    "Evento de Tunguska",
    "Homem melificado",
    "Kopi Luwak",
    "Formiga-pote-de-mel",
    "Lutefisk",
    "Formigas de correição",
    "Macrocheira kaempferi",
    "Lula-colossal",
    "Vampyroteuthis infernalis",
    "Dodecaedro romano",
    "Criptozoologia",
    "Monstro do lago Ness",
    "Pé-grande",
    "Preguiça-gigante",
    "Monstro do Grande Lago",
    "Mothman",
    "Monstro de Flatwoods",
    "Tilikum (orca)",
    "Erupção do Krakatoa em 1883",
    "Batalha de Los Angeles",
    "Zhang Zongchang",
    "Mansa Muça",
    "Lee Miller",
    "Mata Hari",
    "Josephine Baker",
    "Charles J. Guiteau",
    "Hunter S. Thompson",
    "Eva Perón",
    "William McGonagall",
    "Ching Shih",
    "Franz Nopcsa von Felső-Szilvás",
    "Luís II da Baviera",
    "Pu Yi",
    "Basil Zaharoff",
    "Miles Davis",
    "Coco Chanel",
    "Unity Mitford",
    "Georgiana Cavendish, Duquesa de Devonshire",
    "Richard Bong",
    "Christopher Marlowe",
    "Carlos II de Espanha",
    "Joana Grey",
    "Lorde Byron",
    "Charles Bradley",
    "John McAfee",
    "Hedy Lamarr",
    "Paul Erdős",
    "John von Neumann",
    "Calígula",
    "Popeia Sabina",
    "Robert Crumb",
    "Yukio Mishima",
    "Philippe de Rothschild",
    "Chiune Sugihara",
    "Sterling Hayden",
    "Fela Kuti",
    "Wu Zetian",
    "Kim Peek",
    "Ferdinand Porsche",
    "Uday Hussein",
    "Elizabeth Taylor",
    "Zsa Zsa Gábor",
    "Robert Hanssen",
    "Kim Philby",
    "Guy Burgess",
    "Criptoanálise da Máquina Enigma",
    "Kursk (K-141)",
    "Julius e Ethel Rosenberg",
    "NORAD Tracks Santa",
    "Projeto A119",
    "Muro de Berlim",
    "Programa de Contrainteligência",
    "Mulher de Isdalen",
    "Bone Music",
    "UVB-76",
    "Envenenamento de Sergei e Yulia Skripal",
    "Ilha Vozrojdenia",
    "Tsar Bomba",
    "Cicada 3301",
    "D. B. Cooper",
    "Wallace Fard Muhammad",
    "Joyce Vincent",
    "Megumi Yokota",
    "Christopher McCandless",
    "Hinterkaifeck",
    "Morte de Gloria Ramirez",
    "Morte de Elisa Lam",
    "Desaparecimento de Andrew Gosden",
    "Acidente nuclear de Chernobil",
    "Núcleo do Demónio",
    "Gato radioativo",
    "Kit Laboratório de Energia Atômica Gilbert U-238",
    "Garotas do Radium",
    "Mensagens de alerta de resíduos nucleares de longo prazo",
    "Therac-25",
    "Acidente de criticidade de Cecil Kelley",
    "Acidentes nucleares de Tokaimura",
    "Incidente Vela",
    "Acidente radiológico de Goiânia",
    "Daigo Fukuryū Maru",
    "Gianni Versace",
    "Assassino do Zodíaco",
    "Baba Anujka",
    "Béla Kiss",
    "Bunny Man",
    "Assassinatos com Tylenol em Chicago",
    "Okunoshima",
    "Reitoria de Borley",
    "Banho de carne de Kentucky",
    "Epidemia de risos em Tanganica",
    "Caso das Salsichas",
    "Baile dos Ardentes",
    "Grande Fedor",
    "Lisztomania",
    "Balloonfest '86",
    "Incidente Dave Matthews Band",
    "Dança dos Fantasmas",
    "Nongqawuse",
    "Expedição de John Franklin",
    "George Mallory",
    "Sergei Krikalev",
    "Acidente do ônibus espacial Columbia",
    "Acidente do ônibus espacial Challenger",
    "Soyuz 11",
    "Expedição Transantártica Imperial",
    "Expedição Terra Nova",
    "Colônia de Roanoke",
    "Incidente dos envelopes postais da Apollo 15",
    "Expedição Jeannette",
    "Charles Lindbergh",
    "Cosmonautas fantasmas",
    "David Livingstone",
    "Caravana Donner",
    "Expedição Challenger",
    "Igreja da Unificação",
    "Heaven's Gate (seita)",
    "Thomas Cromwell",
    "Medjed",
    "Girolamo Savonarola",
    "Jan Hus",
    "Papado de Avinhão",
    "Jonestown",
    "Cerco de Waco",
    "Ordem do Templo Solar",
    "Papisa Joana",
    "Voo Air Canada 143",
    "Atentado de Lockerbie",
    "Vesna Vulović",
    "Restaurante La Tante DC10",
    "Desastre do Hindenburg",
    "Desastre aéreo de Tenerife",
    "Voo Força Aérea Uruguaia 571",
    "Voo British Airways 5390",
    "Franz Reichelt",
    "Voo Malaysia Airlines 370",
    "Voo American Airlines 191",
    "Voo Japan Airlines 123",
    "AVE Mizar",
    "Colisão aérea de 1945 no Empire State Building",
    "Voo Air New Zealand 901",
    "Voo Korean Air Lines 007",
    "Afundamento da frota alemã em Scapa Flow",
    "Masabumi Hosono",
    "SS United States",
    "USS Scorpion (SSN-589)",
    "Bluebelle",
    "Navios fantasmas norte-coreanos",
    "Batávia (navio de 1628)",
    "Projeto Habacuque",
    "Mary Celeste",
    "RMS Empress of Ireland",
    "SS Andrea Doria",
    "PS General Slocum",
    "Michael Rockefeller",
    "USS Indianapolis (CA-35)",
    "Incêndio no cofre da Fox em 1937",
    "Desabamento da loja de departamentos de Sampoong",
    "Colapso da passarela do Hyatt Regency",
    "Incêndio no The Station Nightclub",
    "Explosão de Halifax",
    "Incêndio na fábrica da Triangle Shirtwaist",
    "O Grito",
    "Assalto ao trem pagador (Inglaterra)",
    "Vincenzo Peruggia",
    "Tiroteio de North Hollywood",
    "Roubo da Lufthansa",
    "Conker's Bad Fur Day",
    "Crise dos jogos eletrônicos de 1983",
    "E.T. the Extra-Terrestrial (jogo eletrônico)",
    "Link: The Faces of Evil e Zelda: The Wand of Gamelon",
    "Plumbers Don't Wear Ties",
    "Grim Fandango",
    "Concurso de matança de cem homens",
    "Microsoft x MikeRoweSoft",
    "Vladimir Demikhov",
    "Experiência de Milgram",
    "Experimento de aprisionamento de Stanford",
    "Leonid Rogozov",
    "Henrietta Lacks",
    "Fibrodisplasia ossificante progressiva",
    "Insônia fatal",
    "Ed Wood",
    "Pulgasari",
    "Titanic (filme de 1943)",
    "The Conqueror",
    "L'Arrivée d'un train en gare de La Ciotat",
    "Roundhay Garden Scene",
    "Holocausto Canibal",
    "Homens e Feras",
    "Budd Dwyer",
    "Dennō Senshi Porygon",
    "A Guerra dos Mundos (rádio)",
    "Interrupção da transmissão da Southern Television",
    "Interrupção no sinal de transmissão do Capitão Midnight",
    "Snuffy's Parents Get a Divorce",
    "Vamos pentear nossos cabelos de acordo com o estilo socialista",
    "Pioneiros do Amanhã",
    "Incidente Max Headroom",
    "Boston Corbett",
    "Stalag Luft III",
    "Henri Charrière",
    "Experimento de Rosenhan",
    "Piotr Kropotkin",
    "Fuga de Alcatraz em junho de 1962",
    "Operação Paperclip",
    "If Day",
    "Operação Carne Moída",
    "Operação Chastise",
    "Estação meteorológica Kurt",
    "Voo 19",
    "Operação Bernhard",
    "V-3",
    "Operação Fortitude",
    "Bruxas da Noite",
    "Plano de guerra vermelho",
    "Jack Churchill",
    "Foo fighter",
    "Raposa-vermelha-doméstica",
    "Loukanikos",
    "Stubby",
    "Unsinkable Sam",
    "Chief Mouser to the Cabinet Office",
    "Explosão de baleias",
    "Mary (elefanta)",
    "Potoooooooo",
    "Hachiko",
    "Laika",
    "Fe, Fi, Fo, Fum e Phooey",
    "Cavalo de mergulho",
    "William Windsor",
    "Blanche Monnier",
    "Irmãos Collyer",
    "Sada Abe",
    "June e Jennifer Gibbons",
    "Edith Bouvier Beale",
    "Índio do Buraco",
    "Genie (criança selvagem)",
    "Diários de Hitler",
    "John Titor",
    "Homem de Piltdown",
    "Embuste de Dreadnought",
    "Parque Haesindang",
    "Museu Falológico Islandês",
    "Ilha das Bonecas",
    "Pruitt-Igoe",
    "Máquina misteriosa de refrigerante de Capitol Hill",
    "Tree That Owns Itself",
    "Ilhas Diomedes",
    "Other World Kingdom",
    "The Million Dollar Homepage",
    "Varosha",
    "Lloyd's Building",
    "Levantamento de Chicago",
    "Aeroporto Internacional Montréal-Mirabel",
    "Hotel Ryugyong",
    "Basílica de Nossa Senhora da Paz de Iamussucro",
    "Habitat 67",
    "Biosfera 2",
    "Ovo centenário",
    "Ovos de virgem",
    "Salmão à lava-louça",
    "Kit Kats no Japão",
    "Milbenkäse",
    "François Vatel",
    "Caso Profumo",
    "Caso Watergate",
    "Caso do colar de diamantes",
    "Impeachment de Park Geun-hye",
    "Jim Bakker",
    "Charles Stewart Parnell",
    "Fala (cão)",
    "Operação Lava Jato",
    "Caso Rojas",
    "Bona Dea",
    "Guerra aos Emus",
    "Wilmer McLean",
    "Simo Häyhä",
    "Jorge Luis Borges",
    "Hotel de Hilbert",
    "Navio de Teseu",
    "Lei de Godwin",
    "Número ilegal",
    "Escolha de Hobson",
    "Efeito Streisand",
    "Paradoxo da Bela Adormecida",
    "Fogo de santelmo",
    "Sinal Wow!",
    "Sexualidade na Roma Antiga",
    "Crianças verdes de Woolpit",
    'Society for the Prevention of Calling Sleeping Car Porters "George"',
    "Amizade",
    "Atletismo nos Jogos Olímpicos de Verão de 1904 - Maratona masculina",
    "English As She Is Spoke",
    "Caso Escola Base",
    "Escândalo da mandioca",
    "Escândalo do Banco Marka",
    "Vazamento de questões do ENEM em 2025",
    "Operação Carne Fraca",
    "Máfia do Lixo de Maceió",
    "Operação Acarajé",
    "Vaza Jato",
    "Apagão aéreo no Brasil em 2006",
    "Escândalo dos atos secretos",
    "Escândalo das passagens aéreas",
    "Renangate",
    "Escândalo dos Sanguessugas",
    "Máfia do Apito",
    "Tiroteio de 1995 na Universidade de São Paulo",
    "Complexo Viário Ayrton Senna",
    "Massacre do Carandiru",
    "Rompimento de barragem em Brumadinho",
    "Ameaças a Marcela Temer",
    "Rompimento de barragem em Mariana",
    "Castor de Andrade",
    "Arlete Hilu",
    "Cabo Bruno",
    "Ezequiel Castanha",
    "Elias Maluco",
    "Dilonei Melara",
    "Márcio Amaro de Oliveira",
    "Marcelo Caron",
    "Maníaco da Capa Preta",
    "Leonardo Pareja",
    "Kat Torres",
    "Júlio Santana",
    "José Maria Marin",
    "Hosmany Ramos",
    "Valdetário Carneiro",
    "PC Farias",
];
