export const arrPaginasObjetivo = [
    "Machado",
    "Canhão",
    "Anzol",
    "Televisor",
    "Extintor",
    "Panela",
    "Papel",
    "Pólen",
    "Caiaque",
    "Fadiga",
    "Gravidez",
    "Biscoito",
    "Leite em pó",
    "Casa",
    "Camuflagem",
    "Garrafa",
    "Circo",
    "Abelha",
    "Microscópio",
    "Dinamite",
    "Telefone",
    "Motor a vapor",
    "Antibiótico",
    "Radar",
    "Óculos",
    "Anestesia",
    "Raios X",
    "Sabão",
    "Queijo",
    "Vinho",
    "Diamante",
];
