export const arrPaginasObjetivo = [
    "Ventilador",
    "Sanguessuga",
    "Pente",
    "Tesoura",
    "Machado",
    "Caneta",
    "Arpão",
    "Canhão",
    "Agulha",
    "Flauta",
    "Rede de pesca",
    "Anzol",
    "Impressora",
    "Sofá",
    "Televisor",
    "Cadeira",
    "Mesa",
    "Fogão",
    "Torradeira",
    "Barbeador",
    "Extintor",
    "Hidrante",
    "Máquina de costura",
    "Cafeteira",
    "Panela",
    "Frigideira",
    "Panela de pressão",
    "Pia",
    "Cama",
    "Balde",
    "Poço",
    "Cofre",
    "Chave",
    "Janela",
    "Vitrine",
    "Porta",
    "Foice",
    "Lápis",
    "Papel",
    "Picareta",
    "Hemorragia",
    "Garimpo",
    "Abóbora",
    "Pólen",
    "Caiaque",
    "Fadiga",
    "Gravidez",
    "Corda",
    "Mochila",
    "Prato",
    "Sopa",
    "Biscoito",
    "Leite em pó",
    "Bolo",
    "Garfo",
    "Faca",
    "Vestido",
    "Casa",
    "Amor",
    "Beijo",
    "Abraço",
    "Luva",
    "Chapéu",
    "Relógio de pulso",
    "Camuflagem",
    "Lego",
    "Espelho",
    "Garrafa",
    "Chaminé",
    "Vaso sanitário",
    "Circo",
    "Abelha",
    "Javali",
    "Raposa",
    "Panqueca",
    "Microscópio",
    "Bússola",
    "Dinamite",
    "Telefone",
    "Motor a vapor",
    "Antibiótico",
    "Radar",
    "Laser",
    "Relógio",
    "Óculos",
    "Anestesia",
    "Raios X",
    "Sabão",
    "Queijo",
    "Vinho",
    "Diamante",
    "Sono",
    "Memória",
];
