export const arrPaginasObjetivo = [
    "Pandemia",
    "Papa",
    "Pólvora",
    "Vulcão",
    "Boxe",
    "Medalha de ouro",
    "Seca",
    "Eclipse solar",
    "Buraco negro",
    "Copa do Mundo FIFA",
    "Maratona",
    "Astronauta",
    "Espada",
    "Voleibol",
    "Surfe",
    "Cirurgia",
    "Skate",
    "Pinguim",
    "Cometa",
    "Satélite",
    "Biblioteca",
    "Deserto",
    "Caatinga",
    "Objeto voador não identificado",
    "Preguiça",
    "Gula",
    "Luxúria",
    "Ira",
    "Inveja",
    "Avareza",
    "Soberba",
    "Machado",
    "Canhão",
    "Anzol",
    "Panela",
    "Papel",
    "Pólen",
    "Caiaque",
    "Fadiga",
    "Gravidez",
    "Biscoito",
    "Leite em pó",
    "Casa",
    "Camuflagem",
    "Garrafa",
    "Abelha",
    "Microscópio",
    "Dinamite",
    "Motor a vapor",
    "Antibiótico",
    "Radar",
    "Óculos",
    "Anestesia",
    "Raios X",
    "Sabão",
    "Queijo",
    "Vinho",
    "Pneu",
    "Motocicleta",
    "Helicóptero",
    "Vinho",
    "Canoa",
    "Cérebro",
    "Cometa Halley",
    "Diamante",
];
