export const arrNovosObjetivos = [
    "Pandemia",
    "Papa",
    "Pólvora",
    "Vulcão",
    "Boxe",
    "Medalha de ouro",
    "Tsunâmi",
    "Seca",
    "Incêndio florestal",
    "Eclipse solar",
    "Buraco negro",
    "Copa do Mundo FIFA",
    "Maratona",
    "astronauta",
    "Espada",
    "Voleibol",
    "Surfe",
    "Cirurgia",
    "Skate",
    "Pinguim",
    "Cometa",
    "Satélite",
    "Biblioteca",
    "Deserto",
    "Caatinga",
    "Objeto voador não identificado",
    "Preguiça",
    "Gula",
    "Luxúria",
    "Ira",
    "Inveja",
    "Avareza",
    "Soberba",
];
