export const arrNovosObjetivos = [
    "Loukanikos",
    "Stubby",
    "Unsinkable Sam",
    "Chief Mouser to the Cabinet Office",
    "Explosão de baleias",
    "Mary (elefanta)",
    "Potoooooooo",
    "Hachiko",
    "Laika",
    "Fe, Fi, Fo, Fum e Phooey",
    "Cavalo de mergulho",
    "William Windsor",
    "Blanche Monnier",
    "Irmãos Collyer",
    "Sada Abe",
    "June e Jennifer Gibbons",
    "Edith Bouvier Beale",
    "Índio do Buraco",
    "Genie (criança selvagem)",
    "Diários de Hitler",
    "John Titor",
    "Homem de Piltdown",
    "Kaspar Hauser",
    "Embuste de Dreadnought",
    "Parque Haesindang",
    "Museu Falológico Islandês",
    "Ilha das Bonecas",
    "Pruitt-Igoe",
    "Máquina misteriosa de refrigerante de Capitol Hill",
    "Tree That Owns Itself",
    "Ilhas Diomedes",
    "Other World Kingdom",
    "The Million Dollar Homepage",
    "Varosha",
    "Lloyd's Building",
    "Levantamento de Chicago",
    "Aeroporto Internacional Montréal-Mirabel",
    "Hotel Ryugyong",
    "Basílica de Nossa Senhora da Paz de Iamussucro",
    "Habitat 67",
    "Biosfera 2",
    "Ovo centenário",
    "Ovos de virgem",
    "Salmão à lava-louça",
    "Kit Kats no Japão",
    "Milbenkäse",
    "François Vatel",
    "Caso Profumo",
    "Caso Watergate",
    "Caso do colar de diamantes",
    "Impeachment de Park Geun-hye",
    "Jim Bakker",
    "Charles Stewart Parnell",
    "Fala (cão)",
    "Operação Lava Jato",
    "Caso Rojas",
    "Bona Dea",
    "Guerra aos Emus",
    "Wilmer McLean",
    "Guerra dos Chimpanzés de Gombe",
    "Simo Häyhä",
    "Jorge Luis Borges",
    "Hotel de Hilbert",
    "Navio de Teseu",
    "Lei de Godwin",
    "Número ilegal",
    "Escolha de Hobson",
    "Efeito Streisand",
    "Paradoxo da Bela Adormecida",
    "Fogo de santelmo",
    "Sinal Wow!",
    "Manuscrito Voynich",
    "Sexualidade na Roma Antiga",
    "Crianças verdes de Woolpit",
    'Society for the Prevention of Calling Sleeping Car Porters "George"',
    "Amizade",
    "Atletismo nos Jogos Olímpicos de Verão de 1904 - Maratona masculina",
    "English As She Is Spoke",
    "Caso Escola Base",
    "Escândalo da mandioca",
    "Escândalo do Banco Marka",
    "Vazamento de questões do ENEM em 2025",
    "Operação Carne Fraca",
    "Máfia do Lixo de Maceió",
    "Operação Acarajé",
    "Vaza Jato",
    "Apagão aéreo no Brasil em 2006",
    "Escândalo dos atos secretos",
    "Escândalo das passagens aéreas",
    "Renangate",
    "Escândalo dos Sanguessugas",
    "Máfia do Apito",
    "Tiroteio de 1995 na Universidade de São Paulo",
    "Complexo Viário Ayrton Senna",
    "Massacre do Carandiru",
    "Rompimento de barragem em Brumadinho",
    "Ameaças a Marcela Temer",
    "Rompimento de barragem em Mariana",
    "Castor de Andrade",
    "Arlete Hilu",
    "Cabo Bruno",
    "Ezequiel Castanha",
    "Elias Maluco",
    "Dilonei Melara",
    "Márcio Amaro de Oliveira",
    "Marcelo Caron",
    "Maníaco da Capa Preta",
    "Leonardo Pareja",
    "Kat Torres",
    "Júlio Santana",
    "José Maria Marin",
    "Hosmany Ramos",
    "Valdetário Carneiro",
    "PC Farias",
];
