export const novasPaginas = [
    "Esposas de Henrique VIII",
    "Cometa de César",
    "Defenestrações de Praga",
    "Arca da Aliança",
    "Biblioteca perdida de Ivã, o Terrível",
    "Saque de Roma (410)",
    "Ouro de Tolosa",
    "Amaro Pargo",
    "Três Irmãos (joia)",
    "Os Juízes Justos",
    "Ovo Fabergé",
    "RMS Republic (1903)",
    "Roubo de diamantes em Antuérpia",
    "Masamune",
    "Comboio fantasma nazi",
    "Câmara de Âmbar",
    "Joias da Coroa Francesa",
    "Lista de papas sexualmente ativos",
    "Orientação do papel higiênico",
    "Lista de guerras por número de mortos",
    "Velha Tjikko",
    "Jaya Sri Maha Bodhi",
    "Adansonia digitata",
    "Árvore do Ténéré",
    "Árvore da Ciência do Bem e do Mal",
    "Cajueiro de Pirangi",
    "Máquina de Anticítera",
    "Mapa de Piri Reis",
    "Grande Mancha Vermelha",
    "Cintura de asteroides",
    "Colina mamelonar",
    "Lao Zi",
    "Preste João",
    "Aláqueme Bianre Alá",
    "Legio IX Hispana",
    "Plínio, o Velho",
    "Plínio, o Jovem",
    "Incitato",
    "Timothy Dexter",
    "Tarrare",
    "Inês de Castro",
    "Sínodo do Cadáver",
    "Nicolau Copérnico",
    "Otto Skorzeny",
    "Adrian Carton de Wiart",
    "Culinária da Escócia",
    "Guerra dos Chimpanzés de Gombe",
    "Batalha de B-R5RB",
    "Nils Olav",
    "Incêndio de uísque em Dublin",
    "TempleOS",
    "Guerra do Porco",
    "Batalha pelo Castelo Itter",
    "Tentativas de assassinato a Fidel Castro",
    "Inundação de melaço de Boston",
    "Olga de Kiev",
    "Unidade 731",
    "Pickles",
    "Flocke",
    "Knut (urso-polar)",
    "Larry (gato)",
    "Paul (polvo)",
    "Messi (cão)",
    "Moo Deng",
    "Nora (gato)",
    "Patron (cão)",
    "Stepan",
    "Blondi",
    "Bucéfalo",
    "Hanno (elefante)",
    "Marengo (cavalo)",
    "Alex (papagaio)",
    "Hans Esperto",
    "Kanzi",
    "Koko (gorila)",
    "Lady Wonder",
    "Jonathan (tartaruga)",
    "Harriet (tartaruga)",
    "George Solitário",
    "Ilha-fantasma",
    "Ilha Nula",
    "Lago Nyos",
    "Escada de Jacó (Jamestown)",
    "Meteorito Hoba",
    "Pedículo do Congo",
    "Akon City (Senegal)",
    "Umoja",
    "Ilha Tromelin",
    "Socotorá",
    "República de Benim (1967)",
    "Cachoeiras de Sangue",
    "Cratera de Darvaza",
    "Principado de Sealand",
    "Placa de reclamação a Ea-nasir",
    "Heliogábalo",
    "Papa Bento IX",
    "Papa Celestino V",
    "Contatos transoceânicos pré-colombianos",
    "Batalhão Sagrado de Tebas",
    "Saneamento na Civilização do Vale do Indo",
    "Silbanaco",
    "Relações sino-romanas",
    "Wise Men of Gotham",
    "Revolta de Nica",
    "João I de França",
    "Verme-da-mongólia",
    "Chupacabra",
    "Drop bear",
    "Besta de Gévaudan",
    "Vaca esférica",
    "Squonk",
    "Tarasca",
    "Demônio de Jersey",
    "Homem do distintivo",
    "Dan Burros",
    "Enterro celestial",
    "Esmagamento por elefante",
    "Fotografia com pombos",
    "Movimento antitabagista na Alemanha nazista",
    "Sentido da vida",
    "Se uma árvore cai em uma floresta",
];
