export const novasPaginasIniciais = [
    "Criptozoologia",
    "Monstro do lago Ness",
    "Pé-grande",
    "Preguiça-gigante",
    "Monstro do Grande Lago",
    "Mothman",
    "Monstro de Flatwoods",
    "Tilikum (orca)",
    "Erupção do Krakatoa em 1883",
    "Batalha de Los Angeles",
    "Zhang Zongchang",
    "Mansa Muça",
    "Lee Miller",
    "Mata Hari",
    "Josephine Baker",
    "Charles J. Guiteau",
    "Phineas Gage",
    "Hunter S. Thompson",
    "Eva Perón",
    "William McGonagall",
    "Ching Shih",
    "Franz Nopcsa von Felső-Szilvás",
    "Luís II da Baviera",
    "Pu Yi",
    "Basil Zaharoff",
    "Miles Davis",
    "Coco Chanel",
    "Unity Mitford",
    "Georgiana Cavendish, Duquesa de Devonshire",
    "Richard Bong",
    "Christopher Marlowe",
    "Carlos II de Espanha",
    "Joana Grey",
    "Lorde Byron",
    "Charles Bradley",
    "John McAfee",
    "Hedy Lamarr",
    "Paul Erdős",
    "John von Neumann",
    "Calígula",
    "Popeia Sabina",
    "Robert Crumb",
    "Yukio Mishima",
    "Philippe de Rothschild",
    "Chiune Sugihara",
    "Sterling Hayden",
    "Fela Kuti",
    "Wu Zetian",
    "Kim Peek",
    "Ferdinand Porsche",
];
