export const arr = [
    "    Hemorragia",
    "    Peste Negra",
    "    Garimpo",
    "    Abóbora",
    "    Geada",
    "    Pólen",
    "    Caiaque",
    "    Fadiga",
    "    Gravidez",
    "    Gêmeos",
    "    Brincadeira",
    "    Vinho",
    "    Limão",
    "    Tangerina",
    "    DVD",
    "    Garrafa",
    "    Barril",
    "    Chaminé",
    "    Vaso sanitário",
    "    Esqueleto",
    "    Tornozelo",
];
